workflows:
  - .github/**/*.yml
documentation:
  - '**/*.md'
dependencies:
  - gradle/libs.versions.toml

data:
  - features/*/data/**
logic:
  - features/*/logic/**
ui-ux:
  - features/*/ui/**
  - core/design
  - core/navigation

core:api:
  - core/api/**
core:compose-logviewer:
  - core/compose-logviewer/**
core:compose-segmentedprogressindicator:
  - core/compose-segmentedprogressindicator/**
core:design:
  - core/design/**
core:navigation:
  - core/navigation/**
core:skeleton:
  - core/skeleton/**
core:strong-result:
  - core/strong-result/**

features:apps:
  - features/apps/**
features:auth:
  - features/auth/**
features:credentials:
  - features/credentials/**
features:dashboard:
  - features/dashboard/**
features:dataprotection:
  - features/dataprotection/**
features:datasets:
  - features/datasets/**
features:network:
  - features/network/**
features:power:
  - features/power/**
features:reporting:
  - features/reporting/**
features:shares:
  - features/shares/**
features:storage:
  - features/storage/**
feature:systemsettings:
  - features/systemsettings/**
features:virtualization:
  - features/virtualization/**
