build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'
  # - 'LicenseHeaderLoaderExtension'

console-reports:
  active: true
  exclude:
     - 'ProjectStatisticsReport'
     - 'ComplexityReport'
     - 'NotificationReport'
     - 'FindingsReport'
     - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
   - 'TxtOutputReport'
   - 'XmlOutputReport'
   - 'HtmlOutputReport'
   - 'MdOutputReport'

comments:
  active: true
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewScreenSize'
      - 'PreviewFontScale'
      - 'PreviewLightDark'
      - 'PreviewDynamicColors'
  UndocumentedPublicProperty:
    active: true

complexity:
  active: true
  LongParameterList:
    active: true
    ignoreDefaultParameters: true
  MethodOverloading:
    active: true
  NamedArguments:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: true
    threshold: 3
  TooManyFunctions:
    active: true
    ignoreOverridden: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

exceptions:
  active: true
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true

naming:
  active: true
  BooleanPropertyNaming:
    active: true
  FunctionMaxLength:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewScreenSize'
      - 'PreviewFontScale'
      - 'PreviewLightDark'
      - 'PreviewDynamicColors'
    excludes:
      - '**/test/**.kt'
  FunctionMinLength:
    active: true
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
  LambdaParameterNaming:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  VariableMaxLength:
    active: true
  VariableMinLength:
    active: true
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

performance:
  active: true
  CouldBeSequence:
    active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  UnnecessaryNotNullCheck:
    active: true

style:
  active: true
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
  BracesOnWhenStatements:
    active: true
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  DataClassContainsFunctions:
    active: true
    conversionFunctionPrefix:
      - 'to'
    allowOperators: true
  DoubleNegativeLambda:
    active: true
  ForbiddenAnnotation:
    active: true
  MagicNumber:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewScreenSize'
      - 'PreviewFontScale'
      - 'PreviewLightDark'
      - 'PreviewDynamicColors'
  MandatoryBracesLoops:
    active: true
  MaxChainedCallsOnSameLine:
    active: true
    maxChainedCalls: 5
  MultilineLambdaItParameter:
    active: true
  MultilineRawStringIndentation:
    active: true
  NoTabs:
    active: true
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
  UnnecessaryLet:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: true
    allowVars: false
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true