name: "Triage"

on:
  - pull_request_target

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/labeler@v4
        with:
          configuration-path: .github/area-labeler.yml
          sync-labels: true
          dot: true

      - uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: 'size:xs'
          s_label: 'size:s'
          m_label: 'size:m'
          l_label: 'size:l'
          xl_label: 'size:xl'
